.gitignore, .idea/compiler.xml, build.gradle, src/main/java/depromeet/batonsearch/domain/Tag/Tag.java, src/main/java/depromeet/batonsearch/domain/Tag/repository/TagRepository.java, src/main/java/depromeet/batonsearch/domain/bookmark/Bookmark.java, src/main/java/depromeet/batonsearch/domain/buy/Buy.java, src/main/java/depromeet/batonsearch/domain/message/Message.java, src/main/java/depromeet/batonsearch/domain/region/Region.java, src/main/java/depromeet/batonsearch/domain/region/repository/RegionRepository.java, src/main/java/depromeet/batonsearch/domain/sell/Sell.java, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/java/depromeet/batonsearch/domain/user/User.java, src/main/java/depromeet/batonsearch/domain/user/repository/UserRepository.java, src/main/java/depromeet/batonsearch/global/config/QueryDslConfig.java, src/main/java/depromeet/batonsearch/global/security/config/WebMvcConfig.java, src/main/java/depromeet/batonsearch/global/swagger/SwaggerConfig.java, src/main/resources/application-dev.yml, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslTest.java
Feature Branch를 사용하지 않음에 따라서, Develop Branch로 merge 하겠습니다.
=> Search Branch To Develop Branch

mysql/table_setting.sql, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/domain/tickettag/TicketTag.java, src/test/java/depromeet/batonsearch/domain/ticket/AllDtoTest.java, src/test/java/depromeet/batonsearch/domain/ticket/EntityLogicTest.java, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslAccuracyTest.java, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslSpeedTest.java
- 날짜 쿼리 추가
- Date -> LocalDate, LocalDateTime으로 변경
=> 2022-04-23

mysql/table_setting.sql, src/main/java/depromeet/batonsearch/domain/buy/Buy.java, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/TicketState.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/domain/user/User.java, src/test/java/depromeet/batonsearch/domain/ticket/AllDtoTest.java, src/test/java/depromeet/batonsearch/domain/ticket/EntityLogicTest.java, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslAccuracyTest.java, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslSpeedTest.java
- Ticket Column 수정
- Buy Entity 추가
=> 2022-04-26

mysql/table_setting.sql, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/global/config/MySQLDialect.java, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslAccuracyTest.java
- Response DTO에 거리 반환 되게 로직 수정
=> 2022-05-03

src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketController.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/global/config/ExceptionControllerAdvice.java
- Ticket Controller 추가
- Exception Controller Advice 추가
- Search DTO 수정
=> 2022-05-08

src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketController.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/global/config/ExceptionControllerAdvice.java
- Ticket Request DTO Validation 정책 변경
- ExceptionControllerAdvice 변경
=> 2022-05-09

mysql/table_setting.sql, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketController.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/resources/application-dev.yml
- Ticket GET, POST API 완성
- 추후 PUT, DELETE도 구현 할 예정입니다.
=> 2022-05-11

src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java
- 거리 연산 쿼리의 위도 경도 에러를 해결 했습니다.
=> fix: Location Query Logic Error

.gitignore, Dockerfile, src/main/resources/application-prod.yml, src/main/resources/application.yml
- Dockerfile Build 추가.
빌드시
```bash
$ docker build --build-arg DB_URL=(DB_URL) --build-arg DB_USER=(유저 명) --build-arg DB_PASSWORD=(비밀번호) -t justkode/spring-boot .
```
이렇게 하면 됩니다.
=> 2022-05-13

src/main/resources/application-prod.yml
=> fix: on-profile -> prod

Dockerfile, src/main/java/depromeet/batonsearch/domain/ticketimage/TicketImage.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
- application.yml 수정
- TIcketImage thumbnailUrl Column 추가
=> 2022-05-15

src/test/java/depromeet/batonsearch/domain/ticket/AllDtoTest.java, src/test/java/depromeet/batonsearch/domain/ticket/EntityLogicTest.java
- DTO Test, Entity Logic Test 수정
- 태그 같은 경우는 아직 정해진게 없어 수정하지 않음.
=> 2022-05-16

.github/workflows/search-api.yml, Dockerfile, build.gradle, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/java/depromeet/batonsearch/domain/ticketimage/TicketImage.java, src/main/java/depromeet/batonsearch/domain/ticketimage/dto/TicketImageResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticketimage/repository/TicketImageRepository.java, src/main/java/depromeet/batonsearch/domain/user/User.java, src/main/java/depromeet/batonsearch/global/config/AwsS3Config.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslAccuracyTest.java
- Ticket에 S3 Upload Logic 추가
- 썸네일 기능 추가
- 이에 따른 Github Action 스크립트 수정
=> 2022-05-18

src/main/java/depromeet/batonsearch/domain/tag/StaticTag.java
=> 2022-05-20

.github/workflows/search-api.yml, Dockerfile, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/global/config/SwaggerSpecConfig.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/main/resources/static/search/swagger.yaml
- Expiry Date Column 추가
- 등록 시 회원제 / 횟수제에 따른 에러 로직 DTO에 추가
- Swagger.yaml 작성
- Dockerfile ENV 변경
=> 2022-05-24

src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java
=> 2022-05-26

src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketController.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/java/depromeet/batonsearch/global/config/NullFilter.java, src/main/java/depromeet/batonsearch/global/config/WebConfig.java, src/main/resources/static/search/swagger.yaml
- null String 예외 로직 추가
- Pagination Logic 최적화
- String Search API 추가
- Count Search API 추가
=> 2022-05-29

src/main/resources/application.yml
- application.yaml profile 적용 안되던 문제 해결
=> 2022-06-02

src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/user/User.java, src/main/java/depromeet/batonsearch/domain/user/dto/UserResponseDto.java
- User Column 수정
- TicketResponseDto 남은 일자 추가
=> 2022-06-04

src/main/java/depromeet/batonsearch/domain/bookmark/repository/BookmarkRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/resources/application.yml, src/main/resources/static/search/swagger.yaml
- TicketResponseDto.Info에 isBookmarked 추가
- 유저 정보 담아서 보낼 시, 유저 관련 Bookmark 여부 반환
=> 2022-06-06

src/main/java/depromeet/batonsearch/global/config/SwaggerSpecConfig.java, src/main/resources/static/auth/swagger.yaml
=> 2022-06-08

src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/TicketSortType.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/resources/static/search/swagger.yaml
- TicketResponseDto.Simple에 조회수, 북마크 수, 타입 추가
- 정렬 로직 추가 (남은 일자, 남은 횟수)
- swagger 수정
=> 2022-06-12

src/main/java/depromeet/batonsearch/domain/ticket/repository/TicketQueryRepository.java
=> 2022-06-12 v2

src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java
- Transactional Annotation 위치 수정
=> 2022-06-13

src/main/java/depromeet/batonsearch/domain/bookmark/repository/BookmarkRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/Ticket.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketController.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketRequestDto.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/resources/static/search/swagger.yaml
- TicketInfo 수정 (bookmarked -> bookmarkId)
- TicketImage Post
- Ticket Modify API
- Ticket Image delete API
=> 2022-06-17

src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java
- Auth Header 수정: REMOTE_USER -> Remote-User
=> 2022-06-18

build.gradle, src/main/java/depromeet/batonsearch/domain/fcm/FCMMessage.java, src/main/java/depromeet/batonsearch/domain/fcm/controller/FCMController.java, src/main/java/depromeet/batonsearch/domain/fcm/dto/FCMRequestDto.java, src/main/java/depromeet/batonsearch/domain/fcm/service/FCMService.java, src/main/java/depromeet/batonsearch/domain/report/TicketReport.java, src/main/java/depromeet/batonsearch/domain/report/UserReport.java, src/main/java/depromeet/batonsearch/domain/report/controller/ReportController.java, src/main/java/depromeet/batonsearch/domain/report/controller/ReportControllerImpl.java, src/main/java/depromeet/batonsearch/domain/report/dto/TicketReportRequestDto.java, src/main/java/depromeet/batonsearch/domain/report/dto/UserReportRequestDto.java, src/main/java/depromeet/batonsearch/domain/report/repository/TicketReportRepository.java, src/main/java/depromeet/batonsearch/domain/report/repository/UserReportRepository.java, src/main/java/depromeet/batonsearch/domain/report/service/ReportService.java, src/main/java/depromeet/batonsearch/domain/report/service/ReportServiceImpl.java, src/main/resources/static/search/swagger.yaml, src/test/java/depromeet/batonsearch/domain/ticket/AllDtoTest.java, src/test/java/depromeet/batonsearch/domain/ticket/EntityLogicTest.java, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslAccuracyTest.java, src/test/java/depromeet/batonsearch/domain/ticket/TicketQueryDslSpeedTest.java
- FCM API 추가
- 신고 API 추가
- 이에 따른 Swagger 수정
=> 2022-06-26

.github/workflows/search-api.yml, build.gradle, src/main/java/depromeet/batonsearch/domain/fcm/controller/FCMController.java, src/main/java/depromeet/batonsearch/domain/fcm/service/FCMService.java
=> 2022-06-27

src/main/java/depromeet/batonsearch/domain/fcm/service/FCMService.java, src/main/java/depromeet/batonsearch/domain/user/User.java, src/main/java/depromeet/batonsearch/domain/user/dto/UserResponseDto.java, src/main/resources/static/search/swagger.yaml
- FCM API 에러 반환하게 수정
- User Respost DTO 수정
=> 2022-06-29

src/main/java/depromeet/batonsearch/domain/fcm/controller/FCMController.java, src/main/java/depromeet/batonsearch/domain/fcm/dto/FCMSetDto.java, src/main/java/depromeet/batonsearch/domain/fcm/service/FCMService.java, src/main/java/depromeet/batonsearch/domain/inquiry/Inquiry.java, src/main/java/depromeet/batonsearch/domain/inquiry/controller/InquiryController.java, src/main/java/depromeet/batonsearch/domain/inquiry/dto/InquiryRequestDto.java, src/main/java/depromeet/batonsearch/domain/inquiry/dto/InquiryResponseDto.java, src/main/java/depromeet/batonsearch/domain/inquiry/repository/InquiryRepository.java, src/main/java/depromeet/batonsearch/domain/inquiry/service/InquiryService.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/java/depromeet/batonsearch/domain/user/User.java, src/main/java/depromeet/batonsearch/domain/user/dto/UserResponseDto.java
- Inquiry 테이블 추가
- User FCM Token Set API 추가
- Inquiry 서비스 함수 추가
=> 2022-08-15

src/main/java/depromeet/batonsearch/domain/inquiry/repository/InquiryRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/controller/TicketControllerImpl.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketService.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/resources/static/search/swagger.yaml
- Ticket Inquiries API
- Swagger 작성
=> 2022-08-20

src/main/java/depromeet/batonsearch/domain/inquiry/dto/InquiryResponseDto.java
- fix: InquiryResponseDto fields
=> 2022-08-30

src/main/java/depromeet/batonsearch/domain/inquiry/Inquiry.java, src/main/java/depromeet/batonsearch/domain/inquiry/repository/InquiryRepository.java, src/main/java/depromeet/batonsearch/domain/inquiry/service/InquiryService.java
fix: Inquiry List bug + isRead Logic
=> 2022-08-31

src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/resources/static/search/swagger.yaml
=> 2022-09-02

src/main/java/depromeet/batonsearch/domain/inquiry/repository/InquiryRepository.java, src/main/java/depromeet/batonsearch/domain/ticket/dto/TicketResponseDto.java, src/main/java/depromeet/batonsearch/domain/ticket/service/TicketServiceImpl.java, src/main/resources/static/search/swagger.yaml
- isInquired 필드 추가
- Swagger 수정
=> 2022-09-17
